# Generated by Django 6.0 on 2025-12-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Day number (1-30)', unique=True)),
                ('title', models.CharField(help_text="Title of the day's topic", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description for the curriculum card')),
                ('concept_content', models.TextField(help_text="Markdown content for 'Concept' section")),
                ('hands_on_content', models.TextField(help_text="Markdown content for 'Hands-on' section")),
                ('outcome', models.CharField(help_text='What the learner will achieve', max_length=255)),
                ('interview_questions', models.TextField(blank=True, help_text='Markdown for interview questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Week number (1-4)', unique=True)),
                ('description', models.TextField(help_text='Overview of what is covered this week')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.day')),
            ],
        ),
    ]
