# Generated by Django 6.0 on 2025-12-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(blank=True, max_length=255, null=True)),
                ('option_4', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.IntegerField(help_text='1 for Option 1, 2 for Option 2, etc.')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='curriculum.day')),
            ],
        ),
    ]
