# Generated by Django 6.0 on 2025-12-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL for the lesson video', null=True),
        ),
    ]
