# Generated by Django 6.0 on 2025-12-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation/Answer for Self-Check questions'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Self Check (Text)')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.IntegerField(blank=True, help_text='1-4 for MCQ. Ignored for Text.', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
