# Generated by Django 6.0 on 2025-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='flashcards',
            field=models.JSONField(blank=True, help_text='JSON list of flashcards', null=True),
        ),
    ]
