# Generated by Django 6.0 on 2025-12-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_day_flashcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL friendly identifier (e.g. 'gcp', 'azure')", unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fa-brands fa-google', help_text='FontAwesome class', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['course', 'number']},
        ),
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.PositiveIntegerField(help_text='Day number (1-30)'),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.PositiveIntegerField(help_text='Week number (1-4)'),
        ),
        migrations.AddField(
            model_name='week',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='curriculum.course'),
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('course', 'number')},
        ),
    ]
