# Generated by Django 6.0 on 2025-12-31 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_course_alter_week_options_alter_day_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_index', models.IntegerField(help_text='Index of the card in the Day.flashcards JSON list')),
                ('box', models.IntegerField(default=1, help_text='Box 1 (Daily) to 5 (Retired)')),
                ('next_review_date', models.DateField(auto_now_add=True)),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day', 'card_index')},
            },
        ),
    ]
