# Generated by Django 6.0 on 2026-01-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_flashcardprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='flashcards',
        ),
        migrations.DeleteModel(
            name='FlashcardProgress',
        ),
    ]
