# Generated by Django 6.0 on 2026-01-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_course_options_alter_userprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.PositiveIntegerField(db_index=True, help_text='Day number (1-45)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.PositiveIntegerField(db_index=True, help_text='Week number (1-4)'),
        ),
    ]
